// Generated by Wrangler on Sun Dec 01 2024 22:16:33 GMT+0900 (Korean Standard Time)
// by running `wrangler types`

interface Env {
	TrafficLightDemoKV: KVNamespace;
	TrafficLightDemo: DurableObjectNamespace<import("./src/index").TrafficLightDemo>;
}
