// Generated by Wrangler on Sun Dec 01 2024 17:05:09 GMT+0900 (Korean Standard Time)
// by running `wrangler types`

interface Env {
	TrafficLightDemo: DurableObjectNamespace<import("./src/index").TrafficLightDemo>;
}
